### ISSUE TITLE
when your source code will be released?

### ISSUE THREAD

**Issue by leepeter2019** [sslab-gatech/winnie#1]
when your source code will be released?
I am looking forward to see your winnie fuzzer in detail.
Thanks.

**Comment by stong** [comment]
We are actively working on this now, it should be out within the next few days.

**Comment by Deeby** [comment]
@stong I can't wait. :)

**Comment by zardus** [comment]
Hello, any update on this? The community is eagerly waiting :-)

**Comment by stong** [comment]
Maybe I should just push what I have and refactor it publicly :)

**Comment by stong** [comment]
For transparency, I'm going to be mirroring my todo list here as well.

TODO

 - [ ] Make bb.py more user friendly
 - [ ] Remove C:\users\user
 - [ ] fix launch options
 - [ ] walkthrough for the toy example
 - [ ] resolve all TODOs
 - [ ] clean up printfs
 - [ ] bb-file verification
 - [ ] process groups
 - [ ] format code (tabs/spaces, indent size, braces)
 - [ ] fuzz_iterations
 - [ ] update help strings
 - [ ] cancelio?
 - [ ] deal with legacy winafl code for the default mode. it probably doesn't even work anymore
 - [ ] destroy_target_process
 - [ ] dbgapi.h
 - [ ] document AFL_SAME_CONSOLE
 - [ ] load_bbs() ?
 - [ ] merge fullspeed.h into forkserver.h
 - [ ] handle persistentmode temrination
 - [ ] HeapEnableTerminationOnCorruption ?
 - [ ] watchdog timer for persistent mode


PRE-RELEASE
 - [ ] test intelpt again
 - [ ] test persistent again
 - [ ] check for handle leaks

**Comment by F-ZhaoYang** [comment]
I can't wait. :)

**Comment by stong** [comment]
Code is pretty much done, after I finish writing some documentation I will release :)

**Comment by stong** [comment]
Done! The fuzzer source code is published

**Comment by zardus** [comment]
Thank you!

**Comment by F-ZhaoYang** [comment]
how to automatic harness?

**Comment by ilvxob** [comment]
Hi 
Thanks a lot for your source code, really good project
It can beat dynamorio and ...
but when will the harness generator be released?

**Comment by stong** [comment]
Harness generator is released.

https://github.com/sslab-gatech/winnie/tree/master/harnessgen
