### ISSUE TITLE
Problem generating csrss_header.h file.

### ISSUE THREAD

**Issue by rish9101** [sslab-gatech/winnie#11]
While running the `gen_csrss_offsets.py` script, I am running into a `KeyError` for `RtlpEnvironLookupTable`. I'm not sure why I get this error since the PDBs from Microsoft server were downloaded correctly.

The exact error generated is.
![image](https://user-images.githubusercontent.com/43873720/134909796-b7566105-35f8-45ba-9f89-c292b155359d.png)

My configuration are:
Python version - 2.7.18 - 64 bit
Windows Build version - 21343.1000

**Comment by stong** [comment]
The link order of ntdll is not stable so the script will not work on all versions. According to the README:

> The fuzzer was tested on Windows 10 x64 [1809 17763.973](tel:1809 17763.973). Any other configurations should be considered as unsupported.

Winnie is only guaranteed to be working for this exact version of Windows. You should install this version, 17763.

Could you please send me your ntdll.dll (from System32 and SysWOW64) please?

**Comment by rish9101** [comment]
Ok. I'll try with that.

Here's the ntdll.dll file - https://drive.google.com/file/d/1ry26kkKyhHDf9HJHUdHi7MFJBtLdO0n5/view?usp=sharing

Here's it's pdb file - https://drive.google.com/file/d/1VVYpF6AQlVfEMFL-wNKAZH4v9PXc3Cjv/view?usp=sharing

**Comment by stong** [comment]
Closed due to inactivity

**Comment by xenomuta** [comment]
@stong first of all, thanks to you and all the team for sharing winnie and coming up with such a clever workaround to forking on Windows.
I'm working some changes on forklib to make winnie work on Windows 11 and stumbled with this same issue. 

Could you share the reasoning behind choosing the `RtlpEnvironLookupTable`  function (now missing from the ntdll.dll) as bounding offset of a range?

I want to understand exactly why this symbol was chosen so I can build a generator that works with any version of ntdll.dll.

**Comment by stong** [comment]
Hi. Apologies for delayed response. I've been very busy lately.

If memory serves, the important fields to zero out are described in this comment here: https://github.com/sslab-gatech/winnie/blob/master/forklib/gen_csrss_offsets.py#L164

So those are the most important fields, namely the Csr related ones. RtlpCurDirRef and RtlpEnvironLookupTable also were important to zero, but I don't know why.

There were many changes from Win10 to Win11. No guarantee if Win11 can be supported, although there's a possibility.

Good luck!
