### ISSUE TITLE
Unicorn 2.0 - Bochs Emulator Support

### ISSUE THREAD

**Issue by UnlimitedChild** [sslab-gatech/winnie#15]
Hello,

there is a suggestion to add some modern emulators Unicorn 2.0 and Bochs Emulator. A couple of examples of available projects can be found here:
https://github.com/nccgroup/TriforceAFL
https://github.com/tigerpuma/Afl_unicorn
https://github.com/AFLplusplus/AFLplusplus

Thanks!

Regards

**Comment by stong** [comment]
This is a cool feature request, but unfortunately we are unable to accept it at this time.
