### ISSUE TITLE
help compiling the project 

### ISSUE THREAD

**Issue by FantasyWarrior** [sslab-gatech/winnie#2]
first, thank you for your hard work for making this tool! it will help a lot and saves a lot of time for others :) 

second, i'm a newbie into fuzzing and i would like to learn more to use winnie, i did read the walkthrough and papers but i'm having trouble compiling the project from the sources, 
is it possible to give the steps on how to do it? because it's my first time using visual studio so i'm not used to it and i'm doing my best to learn.

again thank you for the hard work! and i hope to see videos in the future for this tool :)

**Comment by stong** [comment]
1. You have to generate the csrss offsets for your exact build of Windows (the following instructions are copied from the readme)

![image](https://user-images.githubusercontent.com/14918218/116795211-40e2e400-aaa1-11eb-9119-b0dea62fb7c0.png)

2. You open the project in Visual Studio

3. Set configuration to Release. Use x64 for 64-bit and Win32 for 32-bit build. 64-bit build should be used to fuzz 64-bit program and 32-bit fuzzer for fuzzing 32-bit program.

![image](https://user-images.githubusercontent.com/14918218/116795232-7ab3ea80-aaa1-11eb-9bc6-ed53da46e03b.png)

4. You press Build solution (Ctrl+Shift+B)

**Comment by stong** [comment]
I forgot to add prebuilt binaries for libipt which I added today so the build should be fixed now. I'm dumb
