### ISSUE TITLE
Generating basic block file

### ISSUE THREAD

**Issue by Mipam** [sslab-gatech/winnie#41]
Is there anybody who can point me how to corectly use IDAPython script scripts/ida_basic_blocks.py or scripts for Ghidra to generate basicblocks.bb file?or give me a sample what is inside basic blocks file?

**Comment by stong** [comment]
See scripts/ghidra_basic_blocks.py

However, I recommend using IDA Pro.

Basic blocks file looks like this

```
[example_library.dll]
0x1000,0x400
0x1010,0x410
0x1070,0x470
0x109c,0x49c
0x10ad,0x4ad
...
```

List of `rva,fileoffset`
