### ISSUE TITLE
Strange bug trying to fuzz jq

### ISSUE THREAD

**Issue by leocstone** [sslab-gatech/winnie#44]
I'm trying to fuzz open source JSON parser jq, and the fuzzer will run without crashing, but I get no coverage (new paths). Upon further inspection, I noticed that running a debug build with -debug produces different behavior - the fuzzer crashes shortly after starting, and produces this output:
```
Forkserver loaded - forkserver mode
Forkserver PID: 6400
afl_pipe: \\.\pipe\afl-forkserver-6400
Timeout: 100000ms
Minidumps (WER): enabled
Processor affinity: 0x600000001 (2027918607 cores)
Will look for minidumps in C:\Users\Leo\AppData\Local\CrashDumps
Loading harness: jq\jq_harness.dll
Waiting for the harness...
Target address: 0x0046BBA0 | Iter address: 0x0046BBA0
Early hooking critical functions...
inlinehook 1
inlinehook 2
will copy 191119464782102528 bytes
stolenCount = 191119482006470180
inlinehook 3
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 02A6FB00, 00000005, 00000020, 02A6FBF0)
inlinehook done
inlinehook 1
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 02A6FB00, 00000005, 00000040, 02A6FC2C)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 02A6FB00, 00000005, 00000040, 02A6FBF0)
inlinehook 2
will copy 191119464782102528 bytes
stolenCount = 191119482006470180
inlinehook 3
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 02A6FB00, 00000005, 00000040, 02A6FC2C)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 02A6FB00, 00000005, 00000020, 02A6FBF0)
inlinehook done
-> OK!
Connecting to AFL and returning control to main binary!
WOW!!! GUARD_PAGE!!! ExceptionAddress=0046BBA0 ExceptionInformation=0046BBA0
unpacked?
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F6C4, 00000001, 00000040, 0087F7F0)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F6C4, 00000001, 00000020, 0087F7B4)
WOW!!! Early breakpoint!!! 0046BBA0
Reached our target address breakpoint
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F6C4, 00000001, 00000040, 0087F7F0)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F6C4, 00000001, 00000020, 0087F7B4)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F5D0, 00000005, 00000040, 0087F6FC)
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087F5D0, 00000005, 00000020, 0087F6C0)
Target hook reached!
Unhooking early critical functions...
Intercepted call to NtProtectVirtualMemory(FFFFFFFF, 0087EBE0, 00000005, 00000040, 0087ED0C)
inlineunhook done
inlineunhook done
-> OK!
Installing 12003 breakpoints, this might take a while.....
Installed 12003 breakpoints
Okay, spinning up the forkserver now.
TRACE: Fuzzer asked me to create new child
Child pid: 2068
TRACE: Fuzzer asked me to resume the child
Unexpected suspend count 2: 997
Press enter to exit
```

It looks like something is causing the value of stolenCount to be incorrect. I've attached the binary, harness, input, and basic block list. This bug also appears to happen with two other binaries (smpdf and IrFanView - I can provide harnesses and bbfiles for those too if needed).
[jq.zip](https://github.com/sslab-gatech/winnie/files/8863489/jq.zip)
The command line I'm using is:
`afl-fuzz.exe -d -i jq\in -o ..\results\jq\winnie -t 100000 -I 100000 -- -bbfile jq\bblist_jq.bb -- -harness jq\jq_harness.dll -debug -- jq\jq.exe . @@`

**Comment by stong** [comment]
Looks like you're running in 32bit mode. It will copy `191119464782102528 ` bytes which is 0x2A6FE2400000000. Since size_t on 32-bit program is 4 bytes, the value here is actually zero. The printf statement is wrong and it should be using %ld instead of %lld (https://github.com/sslab-gatech/winnie/blob/ab86024ed26b7345e1a1ca141f9232df87fda222/injected-harness/dllmain.cpp#L314). So I don't think this is necessarily the issue.

Otherwise, I have no idea.

**Comment by leocstone** [comment]
Ah, that makes sense.
I've tested this on Windows 10 Education x64, build 19042.1706, and Windows 10 Pro x64, build 19044.1706. I don't get any new edges for jq or the other two binaries on either version, even on a freshly started machine (with nothing else running). I do get edges with the same command line in persistent mode.

**Comment by stong** [comment]
It could be that version of Windows doesn't like play well with `fork()`. This is because the fork implementation relies on reverse-engineered structures and APIs from ntdll and csrss.exe, and these may have updated.

**Comment by leocstone** [comment]
I believe the immediate crashing on the first iteration (with the unexpected suspend count message) was caused by mixing debug and release forkserver DLLs, because the target actually runs after recompiling everything. Now, I'm observing the same behavior I saw originally in the release build, which is the fuzzer running with no errors but not getting any new edges.
It looks like the target is crashing every iteration, but nothing gets printed in the target window. (If I run the same target in persistent mode, I can see output from the target in the forkserver console.)
I've attached the output of the forkserver console with the debug messages enabled. 
[jq_fork_output.txt](https://github.com/sslab-gatech/winnie/files/8905058/jq_fork_output.txt)

**Comment by stong** [comment]
Unforunately, I have no idea :(

We are going to need to attach debugger to the child and see where it is faulting.

**Comment by leocstone** [comment]
That's okay. Thanks for your help.

**Comment by mineechor** [comment]
@leocstone hello,can you share your harness.cpp with me? Thank you very much!!
