### ISSUE TITLE
result

### ISSUE THREAD

**Issue by mineechor** [sslab-gatech/winnie#52]
![image](https://user-images.githubusercontent.com/80303015/204414337-85e0d71c-cb98-4ddc-85b5-596ff5564aa5.png)
Excuse me, why the last new path shows "odd, check syntax". If there are some mistakes in toy_example.exe?

**Comment by gdynamics** [comment]
I was confused for some time, as well. It took me approximately 5 and a half minutes to get my first crash.

Maybe the lack of "new paths" is due to the simplicity of the program?

![image](https://user-images.githubusercontent.com/17126217/204420506-1b0b0398-c55c-47ed-87d9-b640d5d1e76d.png)
